version: 2
jobs:
  build:
    docker:
      - image: mtranter/sbt-protoc:1.2.8_2.12
    working_directory: ~/sk8r
    steps:
      - checkout
      - restore_cache:
          keys:
            - ivy
      - run:
          command: |
            sbt ";set Global / patchVersion := Some(\"$CIRCLE_BUILD_NUM\");publish;writeVersion"
      - run: git tag $(cat ./version.txt) && git push --tags
      - save_cache:
          key: ivy
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: release
          filters:
            tags:
              ignore: /.*/
